version: "3"
services:
  # userrecognition
  userrecognition:
    container_name: userrecognition
    build:
      context: .
      dockerfile: ./userrecognition/Dockerfile
    networks:
      - red-internal
    external_links:
      - mmla-rabbitmq
    environment:
      - RABBITMQ_HOST=mmla-rabbitmq
      - DETECTOR_NAME=retinaface

  #facedirection
  facedirection:
    container_name: facedirection
    build:
      context: .
      dockerfile: ./facedirection/Dockerfile
    networks:
      - red-internal
    external_links:
      - mmla-rabbitmq
    environment:
      - RABBITMQ_HOST=mmla-rabbitmq

  # lookinghead
  lookinghead:
    container_name: lookinghead
    build:
      context: .
      dockerfile: ./lookinghead/Dockerfile
    networks:
      - red-internal
    external_links:
      - mmla-rabbitmq
    environment:
      - RABBITMQ_HOST=mmla-rabbitmq
      
networks:
  red-internal:
    external: 
      name: mmla-network
  
  #emotion
  # emotion:
  #   container_name: emotion
  #   build:
  #     context: .
  #     dockerfile: ./emotion/Dockerfile
  #   networks:
  #     - red-proxy
  #   environment:
  #     - RABBITMQ_HOST=10.100.6.14

  # #facedirection
  # facedirection:
  #   container_name: facedirection
  #   build:
  #     context: .
  #     dockerfile: ./facedirection/Dockerfile
  #   networks:
  #     - red-proxy
  #   environment:
  #     - RABBITMQ_HOST=10.100.6.14 
  
  # #lookinghead
  # lookinghead:
  #   container_name: lookinghead
  #   build:
  #     context: .
  #     dockerfile: ./lookinghead/Dockerfile
  #   networks:
  #     - red-proxy
  #   environment:
  #     - RABBITMQ_HOST=10.100.6.14 
  
  # #pose
  # pose:
  #   container_name: pose
  #   build:
  #     context: .
  #     dockerfile: ./pose/Dockerfile
  #   networks:
  #     - red-proxy
  #   environment:
  #     - RABBITMQ_HOST=10.100.6.14 

  # #hands
  # hands:
  #   container_name: hands
  #   build:
  #     context: .
  #     dockerfile: ./hands/Dockerfile
  #   networks:
  #     - red-proxy
  #   environment:
  #     - RABBITMQ_HOST=10.100.6.14 